on: [push]

jobs:
  regula_tf_job:
    runs-on: ubuntu-latest
    name: Regula Terraform
    steps:
    - uses: actions/checkout@master
    - uses: fugue/regula-action@v3.2.1
      with:
        input_path: .
        rego_paths: policy_custom_rule/fugue_opa


  regula_tf_plan_job:
    runs-on: ubuntu-latest
    name: Regula on a Terraform plan JSON
    steps:
    - uses: actions/checkout@master
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false
        terraform_version: 1.2
    - run: |
        terraform init
        terraform plan -refresh=false -out="plan.tfplan"
        terraform show -json plan.tfplan > plan.json
      env:
        # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_ACCESS_KEY_ID: "ASIAYZFWRJC4TUW624I3"
        AWS_SECRET_ACCESS_KEY: "Ngq+VNvFESTHVI5H/NQrXr7YA2o+1X8eDqz0nPLy"
        AWS_SESSION_TOKEN: "IQoJb3JpZ2luX2VjEPf//////////wEaCWV1LXdlc3QtMiJHMEUCIQCYrpa3eznIZGLn9AObbwqH1NSK+j+g8t7ac8kfxGAqSwIgAvrB8sI2HuMy42ba3rTbZ+t3QTvXa/+Tb8Im+J/u0gUqnwMIEBADGgw2MDM4MjU3MTk0ODEiDKV6yqPoDngiRknSMyr8AnOBgXg+WXfePtSmcPKobmo4hVc4Zf0DL6lf/L2z6un5lozeFFORRLFEnB/4MopZQa1pWwVOP6Tw6bWkerdusjgF9O8BE8l50G12dHie55W68h3pw+fkj9MwhU+wXRbgpxUr2Sapx9qshlAER2qT/W70QAUKI6ztTFoFyQPi0DA/WobdCIzPxT20Hoyg2Amf9BG1LgUCGXSyCIhPHZVERXbNn7XUx4Tcx6LMrOjkRfwkY7xbxYZKMzkFaQk7t4zMu2s6Bls3SLCwX4Gl6ritp0tRQ2BT7f0IbqhohxE9Fyw6tBCM8f3I7Fv7y5RvXk6RRhNamTjEG+IApvRb1vTKZQitWKEu5DuxmSqCeGaKdOlpOAivk5pyd1qyl/7X+mM9pGKqV2ixmwzpP8CVH9MF8+sKKDx2fnXe6o2TFXydI7DPtqGxvn6Eug9+Sx5dczfh209JmKG9Y3oiMp7j9fyQX9U9akW26GIPI1UP0Z9alsHRnD/WnPXrSa4rkh/RMID2tbYGOqYBjDbPBuu6w3ySGQdGRuKOIDUsBIBeAg+HoqabGk4ny/e8KpROwa5kmu1O1S3jUjFN0OZcfrCbcP5+FQrkQiaZG59lWc4RQxSHncmziPbq1RzMsIqedy/tu+AUGzcY3dtkOieplrw/KF+psC208ChR/9wHLN5gtQhaCOX4zVcdkmR6NR5K9qDLKMJJsldnnGA7QR5VQGjZyKZl58FX13zRzO5RnE6XQw=="

    - uses: fugue/regula-action@v3.2.1
      with:
        input_path: ./plan.json
        input_type: tf-plan
        rego_paths: policy_custom_rule/fugue_opa
