on: [push]

jobs:
  regula_tf_job:
    runs-on: ubuntu-latest
    name: Regula Terraform
    steps:
    - uses: actions/checkout@master
    - uses: fugue/regula-action@v3.2.1
      with:
        input_path: .
        rego_paths: policy_custom_rule/fugue_opa


  regula_tf_plan_job:
    runs-on: ubuntu-latest
    name: Regula on a Terraform plan JSON
    steps:
    - uses: actions/checkout@master
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false
        terraform_version: 1.2
    - run: |
        terraform init
        terraform plan -refresh=false -out="plan.tfplan"
        terraform show -json plan.tfplan > plan.json
      env:
        # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_ACCESS_KEY_ID: "ASIAYZFWRJC4QACE35JJ"
        AWS_SECRET_ACCESS_KEY: "95/J+o50YGyqP8NDrMbGuR+AinnC5GQe+ZURnowa"
        AWS_SESSION_TOKEN: "IQoJb3JpZ2luX2VjED4aCWV1LXdlc3QtMiJHMEUCIFQrCn2KpsWVhU9V7vHfafh6PvHFddS6SOjTNG/QWvVAAiEAiYyOh2UBJXorVLYoAQQORm4uJB93IY8zGUbHCbda9V8qnwMIVhADGgw2MDM4MjU3MTk0ODEiDDMq+djvSs00cOHR0ir8AjlfVUQG5/6eBP1CwY/+5G9X8jBf0WZUG3/p2DmBcHP7sFFm4LS/pJlMaJjNV5wpm9HivKVTWB4fz+Z3OZRrk/kOfKvVwBG/soSEreZKjSZgU1Oo3pEXPx3wBnCn11rWhYDXXWySWodiPe0ZaZH2dD+E3j1EgZkW9bb7P7I4ky6bLpdVhffYGfN+ToDL5Ea3DsIhbIBnkoDUgfXCFYJy0494mxN4JfQx7U315EMEwkvNrZuuUvXpw4/D5rBUyNlXQyGq4JHKjb5jDmjRr9SF3M4PaGAMhSlzeOF+fZnyp1keGaje+EeYEr+wJBKmNdAQ0ZpCLXBU4+awo1lO1O8Cij5TLpJb9ubfGm9uBwbKQDBrY7waB5JnrJ+8K1YlQUZWsE2NFYc/t8mPMqKq9HorrgBQgHvzCbDiiduSoV87ALETFJpeqcvafv76z9L0XI9ctXG6O8fuXuxppt6fUR2upu6UQe4HXs5w6lVjb1ESjv+qMassm6sfLqcXKc+5MK6txbYGOqYBERr5gBuozKxnzwxrlmNqP0HC4AQGPym8G+PYzBOOqIffoZw7xb07r4rpmHU5oYaWYINzGDIM3oiTE2FpEzOIN7pN5/aTSQHjcYbLmHBCR6vJNvcOxoSdsnUfUE9vCEC5zWoEQ7/wIiE1bWhTF/ySH1mazUOjQiltoL+AkNIArKRRdY2+yamuOKDlCWtGnFL7URdI/BTkr1JkZbAW7rWAUxO9a8dlaw=="

    - uses: fugue/regula-action@v3.2.1
      with:
        input_path: ./plan.json
        input_type: tf-plan
        rego_paths: policy_custom_rule/fugue_opa
